// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BusEmitInput = { label: string, input_interface: string, input_channels: Array<number>, output_interface: string, output_channels: Array<number>, };
