// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BusInputGroupEmitInput } from "./BusInputGroupEmitInput";
import type { BusOutputEmitInput } from "./BusOutputEmitInput";

export type BusEmitInput = { label: string, 
/**
 * Human-readable name when it differs from the sanitized identifier, e.g. "PQ>MM"
 */
display_name: string | null, 
/**
 * Deprecated: use `input_groups` for multi-port bus inputs.
 */
input_interface: string, 
/**
 * Deprecated: use `input_groups` for multi-port bus inputs.
 */
input_channels: Array<number>, input_groups: Array<BusInputGroupEmitInput>, output_interface: string, output_channels: Array<number>, 
/**
 * Named outputs (e.g. [{name: "Main Output", interface: "Matrix_Out", channels: [1, 2]}])
 */
named_outputs: Array<BusOutputEmitInput>, };
