// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";
import type { Span } from "./Span";

export type BusEntry = { name: string, 
/**
 * Human-readable display name. May contain characters invalid in identifiers
 * (e.g. `"SPOTIFY>FOH"`). The `name` field remains the stable cross-reference key.
 */
label: string | null, inputs: Array<PortRef>, outputs: Array<PortRef>, span: Span, };
