// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BusInputGroup = { input_instance?: string, input_port: string, input_channels: Array<number>, };
