// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BusInputGroup } from "./BusInputGroup";
import type { BusNamedOutput } from "./BusNamedOutput";
import type { InsertEndpoint } from "./InsertEndpoint";

export type BusLoadOutput = { name: string, display_name: string | null, 
/**
 * Deprecated: use `input_groups` for multi-port bus inputs.
 */
input_port: string, 
/**
 * Deprecated: use `input_groups` for multi-port bus inputs.
 */
input_channels: Array<number>, input_groups: Array<BusInputGroup>, named_outputs: Array<BusNamedOutput>, 
/**
 * Bus insert legs — ordered, `[L]` mono, `[L, R]` stereo. See issue #31.
 *
 * Unlike `input_groups`/`named_outputs` above, these are NOT grouped by
 * `(instance, port)` and NOT channel-unioned. Bus inputs are set-like so grouping
 * them is correct; insert legs are an ordered list where a port legitimately
 * repeats (`send: MADI[3], MADI[10]`), so grouping would reorder the stereo pair.
 */
insert_send: Array<InsertEndpoint>, insert_return: Array<InsertEndpoint>, };
