// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BusNamedOutput = { name: string, output_port: string, output_channels: Array<number>, };
