// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BusOutputEmitInput = { name: string, instance: string | null, interface: string, channels: Array<number>, };
