// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";
import type { Span } from "./Span";

export type BusOutput = { 
/**
 * User-defined name for this output, e.g. "Link 1-L". Required, non-empty.
 */
label: string, 
/**
 * Where this output is routed. Empty = declared but unrouted.
 */
destinations: Array<PortRef>, span: Span, };
