// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardEmitInput } from "./CardEmitInput";
import type { ConnectionEmitInput } from "./ConnectionEmitInput";
import type { InstanceEmitInput } from "./InstanceEmitInput";

export type CanvasEmitInput = { instances: Array<InstanceEmitInput>, connections: Array<ConnectionEmitInput>, manufacturer_cards: Array<CardEmitInput>, };
