// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardTemplateOutput } from "./CardTemplateOutput";
import type { ConnectionLoadOutput } from "./ConnectionLoadOutput";
import type { InstanceLoadOutput } from "./InstanceLoadOutput";
import type { RingLoadOutput } from "./RingLoadOutput";

export type CanvasLoadOutput = { instances: Array<InstanceLoadOutput>, connections: Array<ConnectionLoadOutput>, card_templates: Array<CardTemplateOutput>, rings: Array<RingLoadOutput>, };
