// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortLoadOutput } from "./PortLoadOutput";

export type CardTemplateOutput = { template_name: string, manufacturer: string | null, model: string | null, fits: string | null, ports: Array<PortLoadOutput>, };
