// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardSlotGroupOutput = { label: string, slot_count: number, slot_format: string, direction: string, channel_count: number, };
