// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceEmitInput } from "./InterfaceEmitInput";

export type CardEmitInput = { template_name: string, manufacturer: string | null, model: string, fits: string, interfaces: Array<InterfaceEmitInput>, };
