// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsertEndpoint } from "./InsertEndpoint";

export type ChannelLabelOutput = { channel_index: number, label: string, phantom: boolean, propagated: boolean, source_type: string | null, capsule: string | null, rf_band: string | null, 
/**
 * Channel insert legs — ordered, `[L]` mono, `[L, R]` stereo. See issue #31 and
 * `builder::insert_endpoints`. Order is significant; never grouped or unioned.
 * Empty means absent — a plain `Vec` rather than `Option<Vec>` because ts-rs
 * ignores `skip_serializing_if` and the `Option` would need `#[ts(optional)]`
 * to stay honest (see `skip_serialized_option_fields_are_ts_optional` below).
 */
insert_send: Array<InsertEndpoint>, insert_return: Array<InsertEndpoint>, 
/**
 * Every label property that has no dedicated field above, verbatim.
 *
 * Without this, any key outside the fixed struct was silently dropped on load —
 * the reason `insert`/`stand`/`gain` had to live in the layout sidecar (#31).
 *
 * Deliberately UNLIKE `ConnectionLoadOutput::properties`, which also keeps the
 * keys that have dedicated fields: `is_backbone` and friends are a *lossless*
 * re-read of their string, whereas `insert_send`'s typed field is a *lossy parse*.
 * If both carried it and the typed field won on re-emit, a malformed-but-intact
 * source string would be blanked by the very fix meant to preserve it. So a key
 * lives in exactly one place: parsed cleanly → typed field, key removed here;
 * malformed → typed field empty, key stays here and re-emits byte-for-byte.
 *
 * BTreeMap, not HashMap: HashMap iteration order is non-deterministic, which makes
 * emit → load → emit reorder properties each run and breaks idempotency.
 */
properties: { [key in string]?: string }, };
