// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelLabelEmitInput = { channel_index: number, label: string, phantom: boolean, propagated: boolean, source_type: string | null, capsule: string | null, rf_band: string | null, };
