// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsertEndpoint } from "./InsertEndpoint";

export type ChannelLabelEmitInput = { channel_index: number, label: string, phantom: boolean, propagated: boolean, source_type: string | null, capsule: string | null, rf_band: string | null, 
/**
 * Channel insert legs — ordered, `[L]` mono, `[L, R]` stereo (issue #31).
 *
 * `#[serde(default)]` is REQUIRED, same reason as `RouteRuleEmitInput::from_start`
 * above: a frontend built against older WASM omits these entirely, and without the
 * default serde rejects the whole payload with "missing field `insert_send`".
 */
insert_send: Array<InsertEndpoint>, insert_return: Array<InsertEndpoint>, 
/**
 * Label properties with no dedicated field above, emitted verbatim. Round-trips
 * with `ChannelLabelOutput::properties` — see that field for the ownership rule.
 */
properties: { [key in string]?: string }, };
