// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelMappingEmitInput = { from_channel: number, to_channel: number, 
/**
 * "forward" | "return" | "direct"
 */
mapping_type: string, };
