// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelLabelEmitInput = { channel_index: number, label: string, phantom: boolean, };
