// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphLevel } from "./GraphLevel";
import type { SignalIdentity } from "./SignalIdentity";
import type { StreamIdentity } from "./StreamIdentity";

/**
 * Top-level result from `compile_to_graph`.
 */
export type CompileToGraphResult = { levels: { [key in string]?: GraphLevel }, signals: { [key in string]?: SignalIdentity }, streams: { [key in string]?: StreamIdentity }, };
