// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { PortRef } from "./PortRef";

/**
 * A label entry inside a config block.
 */
export type ConfigLabel = { port: PortRef, label: string, properties: Array<KeyValue>, };
