// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigLabel } from "./ConfigLabel";
import type { Span } from "./Span";

export type ConfigDecl = { name: string, labels: Array<ConfigLabel>, span: Span, };
