// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMappingOutput } from "./ChannelMappingOutput";

export type ConnectionLoadOutput = { from_instance: string, to_instance: string, from_port: string, to_port: string, is_backbone: boolean, channel_mappings: Array<ChannelMappingOutput>, from_slot: string | null, to_slot: string | null, 
/**
 * Raw mapping text from PatchLang (e.g. "offset -8", "1->3, 2->4") for TypeScript to process
 */
mapping_text: string | null, };
