// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { PortRef } from "./PortRef";
import type { Span } from "./Span";

export type ConnectDecl = { source: PortRef, target: PortRef, properties: Array<KeyValue>, suppressions: Array<string>, mapping: string | null, span: Span, };
