// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMappingOutput } from "./ChannelMappingOutput";

export type ConnectionLoadOutput = { from_instance: string, to_instance: string, from_port: string, to_port: string, is_backbone: boolean, channel_mappings: Array<ChannelMappingOutput>, from_slot: string | null, to_slot: string | null, 
/**
 * Raw mapping text from PatchLang (e.g. "offset -8", "1->3, 2->4") for TypeScript to process
 */
mapping_text: string | null, 
/**
 * All `connect { ... }` properties verbatim (cable, length, redundant_cable, …).
 *
 * `backbone`/`kind`/`from_slot`/`to_slot` are ALSO surfaced as dedicated fields above
 * because they drive behaviour; they stay in here too so a round-trip re-emits the
 * block unchanged. Previously nothing but those four crossed the boundary, so every
 * other property was silently dropped on load. See FrontendV1#202.
 * BTreeMap, not HashMap: HashMap iteration order is non-deterministic, which made
 * emit -> load -> emit produce the same properties in a different order each run and
 * broke idempotency. Sorted by key is stable and predictable.
 */
properties: { [key in string]?: string }, };
