// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMappingEmitInput } from "./ChannelMappingEmitInput";
import type { KvEmitInput } from "./KvEmitInput";

export type ConnectionEmitInput = { from_instance_name: string, to_instance_name: string, from_port_id: string, to_port_id: string, is_backbone: boolean, channel_mappings: Array<ChannelMappingEmitInput>, properties: Array<KvEmitInput>, };
