// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortInfo } from "./PortInfo";

/**
 * A device/instance node in the graph.
 */
export type DeviceNode = { id: string, label: string, templateName: string, ports: Array<PortInfo>, properties: { [key in string]?: string }, drillable: boolean, };
