// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DRCLayer } from "./DRCLayer";
import type { Severity } from "./Severity";
import type { Span } from "./Span";

/**
 * A single design rule violation or advisory.
 */
export type Diagnostic = { severity: Severity, layer: DRCLayer, message: string, span?: Span, source?: string, target?: string, fix?: string, };
