// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which validation layer produced this diagnostic.
 */
export type DRCLayer = "structural" | "direction" | "mechanical" | "electrical" | "logical" | "temporal" | "ring" | "network" | "flow" | "convention" | "trace";
