// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An edge between two ports.
 */
export type GraphEdge = { id: string, sourceNode: string, sourcePort: string, targetNode: string, targetPort: string, edgeType: string, properties: { [key in string]?: string }, busId: string | null, busIndex: number | null, busSize: number | null, };
