// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceNode } from "./DeviceNode";
import type { GraphEdge } from "./GraphEdge";

/**
 * A single level in the hierarchical graph ("root" or a drillable instance).
 */
export type GraphLevel = { id: string, parentId: string | null, label: string, nodes: { [key in string]?: DeviceNode }, edges: { [key in string]?: GraphEdge }, };
