// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexElement = { "type": "Single", value: number, } | { "type": "Range", start: number, end: number, } | { "type": "Auto" };
