// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One leg of an insert send or return.
 *
 * Same-device by convention — the frontend's `InsertEndpoint` points at an interface
 * on the SAME device. `instance` exists only so an instance-qualified reference
 * round-trips unchanged if one ever appears; nothing is built on it.
 */
export type InsertEndpoint = { instance?: string, port: string, channel: number, };
