// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BusEntry } from "./BusEntry";
import type { KeyValue } from "./KeyValue";
import type { RouteEntry } from "./RouteEntry";
import type { SlotAssignment } from "./SlotAssignment";
import type { Span } from "./Span";

export type InstanceDecl = { name: string, template_name: string, args: Array<KeyValue>, version_constraint: string | null, properties: Array<KeyValue>, routes: Array<RouteEntry>, buses: Array<BusEntry>, slot_assignments: Array<SlotAssignment>, span: Span, };
