// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledCardEmitInput = { slot_label: string, slot_index: number, card_template_name: string, };
