// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BusOutput } from "./BusOutput";
import type { CardSlotGroupOutput } from "./CardSlotGroupOutput";
import type { ChannelLabelOutput } from "./ChannelLabelOutput";
import type { InstalledCardOutput } from "./InstalledCardOutput";
import type { PortLoadOutput } from "./PortLoadOutput";
import type { RouteRuleOutput } from "./RouteRuleOutput";
import type { StreamOutput } from "./StreamOutput";

export type InstanceLoadOutput = { name: string, template_name: string, manufacturer: string | null, model: string | null, category: string | null, kind: string | null, location: string | null, dante_chipset: string | null, rf_subtype: string | null, rf_min_channels: number | null, rf_max_channels: number | null, rf_band: string | null, rf_active_channels: number | null, iem_modes: string | null, ports: Array<PortLoadOutput>, card_slot_groups: Array<CardSlotGroupOutput>, installed_cards: Array<InstalledCardOutput>, 
/**
 * keyed by port name (canonical, directional)
 */
channel_labels: { [key in string]?: Array<ChannelLabelOutput> }, 
/**
 * Template-level bridges (e.g. `bridge Mic_In -> Dante_Out`) → UserDevice.routeRules
 */
route_rules: Array<RouteRuleOutput>, 
/**
 * Per-instance route entries (`route A[n] -> B[m]` in instance body) → pd.internalRoutes
 */
instance_routes: Array<RouteRuleOutput>, internal_buses: Array<BusOutput>, tx_streams: Array<StreamOutput>, rx_streams: Array<StreamOutput>, is_ring_container: boolean, ring_protocol: string | null, };
