// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterfaceEmitInput = { id: string, label: string, 
/**
 * "in" | "out" | "io" | "asymmetric"
 */
direction: string, connector: string | null, transport: string | null, channel_count: number, attributes: Array<string>, };
