// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KvValue } from "./KvValue";

export type KeyValue = { key: string, value: KvValue, };
