// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";

/**
 * Value in a key-value property pair.
 */
export type KvValue = { "kind": "Str", value: string, } | { "kind": "Num", value: number, } | { "kind": "PortRef" } & PortRef;
