// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectDecl } from "./ConnectDecl";
import type { KeyValue } from "./KeyValue";
import type { Span } from "./Span";

export type LinkGroupDecl = { name: string, connects: Array<ConnectDecl>, properties: Array<KeyValue>, span: Span, };
