// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { NetworkMember } from "./NetworkMember";
import type { Span } from "./Span";

export type NetworkDecl = { name: string, properties: Array<KeyValue>, members: Array<NetworkMember>, span: Span, };
