// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkMemberLoadOutput = { member_type: string, instance_name: string, port_group: string | null, slot_index: number | null, };
