// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * A member of a `network` block.
 */
export type NetworkMember = { "kind": "DeviceLevel", instance: string, span: Span, } | { "kind": "PortGroup", instance: string, port_group: string, span: Span, } | { "kind": "SlotRef", instance: string, index: number, span: Span, };
