// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkMemberLoadOutput } from "./NetworkMemberLoadOutput";

export type NetworkLoadOutput = { name: string, protocol: string | null, label: string | null, members: Array<NetworkMemberLoadOutput>, };
