// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamValue } from "./ParamValue";

/**
 * A template parameter with a name and default value.
 */
export type ParamDef = { name: string, default_value: ParamValue, };
