// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Value in a key-value pair: string, number, or port reference.
 */
export type ParamValue = { "type": "Str", value: string, } | { "type": "Num", value: number, };
