// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParseError } from "./ParseError";
import type { PatchProgram } from "./PatchProgram";

/**
 * Result of parsing — may contain both a partial AST and errors.
 */
export type ParseResult = { program: PatchProgram, errors: Array<ParseError>, };
