// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Statement } from "./Statement";

/**
 * Top-level program — a list of statements.
 */
export type PatchProgram = { statements: Array<Statement>, };
