// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortLoadOutput = { name: string, 
/**
 * "in" | "out" | "io"
 */
direction: string, connector: string | null, channel_count: number, transport: string | null, attributes: Array<string>, };
