// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of a connection an auto-resolution applies to.
 */
export type PortSide = "Source" | "Target";
