// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { PortDirection } from "./PortDirection";
import type { RangeSpec } from "./RangeSpec";
import type { Span } from "./Span";

export type PortDef = { name: string, range: RangeSpec | null, direction: PortDirection, connector: string | null, attributes: Array<string>, named_attributes: Array<KeyValue>, span: Span, };
