// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A port on a device node.
 */
export type PortInfo = { id: string, name: string, direction: string, connector?: string, attributes: Array<string>, connected?: boolean, signalNames?: Array<string>, label?: string, labelProperties?: { [key in string]?: string }, 
/**
 * Scene interface ID: `pl::{TemplateName}::{PortDefName}`.
 * Groups ranged ports under one key per definition (e.g., `Mic_In`, not `Mic_In_1`).
 */
sourceKey?: string, };
