// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingMemberOutput } from "./RingMemberOutput";

export type RingLoadOutput = { name: string, protocol: string | null, members: Array<RingMemberOutput>, };
