// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

export type RingMember = { instance_name: string, port_name: string | null, span: Span, };
