// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { RingMember } from "./RingMember";
import type { Span } from "./Span";

export type RingDecl = { name: string, properties: Array<KeyValue>, members: Array<RingMember>, span: Span, };
