// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteRuleEmitInput = { from_interface: string, from_channel: number, to_interface: string, to_channel: number, };
