// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteRuleEmitInput = { from_interface: string, from_channel: number, 
/**
 * Optional owning instance of the `from` port. `None` = the instance that
 * owns this route (same-instance route). `Some(name)` = a paired/other
 * instance, e.g. a Backbone-paired Engine↔Surface cross-instance route.
 */
from_instance?: string, to_interface: string, to_channel: number, 
/**
 * Optional owning instance of the `to` port. See `from_instance`.
 */
to_instance?: string, };
