// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteRuleOutput = { from_port: string, 
/**
 * Deprecated: use `from_start`/`from_end` for the full span.
 */
from_channel: number, from_start: number, from_end: number, 
/**
 * Owning instance of the `from` port when it's a cross-instance reference
 * (e.g. a Backbone-paired Engine↔Surface route). `None` for same-instance.
 */
from_instance?: string, to_port: string, 
/**
 * Deprecated: use `to_start`/`to_end` for the full span.
 */
to_channel: number, to_start: number, to_end: number, 
/**
 * Owning instance of the `to` port when it's a cross-instance reference.
 */
to_instance?: string, };
