// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";
import type { Span } from "./Span";

export type RouteEntry = { source: PortRef, target: PortRef, span: Span, };
