// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteRuleOutput = { from_port: string, from_channel: number, to_port: string, to_channel: number, };
