// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signal identity metadata.
 */
export type SignalIdentity = { name: string, label: string, originNode: string | null, originPort: string | null, };
