// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { RangeSpec } from "./RangeSpec";
import type { Span } from "./Span";

export type SlotDef = { name: string, range: RangeSpec | null, slot_type: string, properties: Array<KeyValue>, span: Span, };
