// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Byte-offset span in the source text.
 * The optional `file` field tracks which file this span belongs to
 * in multi-file compilation (index into a file table).
 */
export type Span = { start: number, end: number, file: number | null, };
