// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeDecl } from "./BridgeDecl";
import type { BridgeGroupDecl } from "./BridgeGroupDecl";
import type { ConfigDecl } from "./ConfigDecl";
import type { ConnectDecl } from "./ConnectDecl";
import type { FlagDecl } from "./FlagDecl";
import type { InstanceDecl } from "./InstanceDecl";
import type { LinkGroupDecl } from "./LinkGroupDecl";
import type { RingDecl } from "./RingDecl";
import type { SignalDecl } from "./SignalDecl";
import type { Span } from "./Span";
import type { StreamDecl } from "./StreamDecl";
import type { TemplateDecl } from "./TemplateDecl";
import type { UseDecl } from "./UseDecl";

/**
 * A top-level statement.
 */
export type Statement = { "type": "Template" } & TemplateDecl | { "type": "Instance" } & InstanceDecl | { "type": "Connect" } & ConnectDecl | { "type": "Bridge" } & BridgeDecl | { "type": "BridgeGroup" } & BridgeGroupDecl | { "type": "LinkGroup" } & LinkGroupDecl | { "type": "Signal" } & SignalDecl | { "type": "Flag" } & FlagDecl | { "type": "Stream" } & StreamDecl | { "type": "Config" } & ConfigDecl | { "type": "Use" } & UseDecl | { "type": "Ring" } & RingDecl | { "type": "Error" } & Span;
