// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stream identity metadata.
 */
export type StreamIdentity = { name: string, properties: { [key in string]?: string }, sourceNode: string | null, sourcePort: string | null, };
