// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { PortRef } from "./PortRef";
import type { Span } from "./Span";

export type StreamDecl = { name: string, properties: Array<KeyValue>, source: PortRef | null, span: Span, };
