// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamEmitInput = { label: string, protocol: string, channel_count: number, interface_id: string, 
/**
 * Ordered indices into the source interface's channels (#37). Position is
 * significant — an AES67 receiver maps by position, so this is never sorted.
 * Empty means "the whole interface", which emits exactly as before.
 *
 * `#[serde(default)]` is REQUIRED: frontend payloads written before #37 omit
 * the field entirely, and without it every one of them fails to deserialize.
 */
source_channels: Array<number>, };
