// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamOutput = { label: string, protocol: string, channel_count: number, port_name: string, direction: string, 
/**
 * Ordered indices into the source interface's channels (#37), flattened from the
 * source port ref's index spec. Empty when the stream selects the whole interface.
 */
source_channels: Array<number>, };
