// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeDecl } from "./BridgeDecl";
import type { ConnectDecl } from "./ConnectDecl";
import type { InstanceDecl } from "./InstanceDecl";
import type { KeyValue } from "./KeyValue";
import type { ParamDef } from "./ParamDef";
import type { PortDef } from "./PortDef";
import type { SlotDef } from "./SlotDef";
import type { Span } from "./Span";

export type TemplateDecl = { name: string, params: Array<ParamDef>, version: string | null, meta: Array<KeyValue>, ports: Array<PortDef>, bridges: Array<BridgeDecl>, instances: Array<InstanceDecl>, connects: Array<ConnectDecl>, slots: Array<SlotDef>, span: Span, };
